# Generated by Django 3.2.5 on 2022-10-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('level', models.CharField(blank=True, max_length=70)),
                ('position', models.CharField(blank=True, choices=[('President', 'President'), ('Vice President', 'Vice President'), ('General Secretary', 'General Secretary'), ('Assistant General Secretary', 'Assistant General Secretary'), ('Financial Secretary', 'Financial Secretary'), ('Welfare Director', 'Welfare Director'), ('Hardware Director', 'Hardware Director'), ('Software Director', 'Software Director'), ('Sports Director', 'Sports Director'), ('Social Director', 'Social Director'), ('Public Relations Officer', 'Public Relations Officer')], max_length=80)),
                ('votes', models.IntegerField(default=0)),
                ('image', models.FileField(null=True, upload_to='media/images/candidates')),
            ],
        ),
    ]
